# Generated by Django 5.2.8 on 2025-11-15 09:21

import django.db.models.deletion
import django_countries.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('NORMAL', 'Normal'), ('ADMIN', 'Admin')], max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('AGENCY', 'Agency')], max_length=20)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('is_verified_provider', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('kyc_document_type', models.CharField(blank=True, max_length=100)),
                ('kyc_document_number', models.CharField(blank=True, max_length=100)),
                ('kyc_document_file', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('payout_method', models.CharField(blank=True, choices=[('BANK', 'Bank'), ('BKASH', 'Bkash'), ('NAGAD', 'Nagad')], max_length=20)),
                ('payout_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('preferred_language', models.CharField(blank=True, max_length=20)),
                ('preferred_currency', models.CharField(blank=True, max_length=20)),
                ('travel_style', models.CharField(blank=True, choices=[('BUDGET', 'Budget'), ('LUXURY', 'Luxury'), ('ADVENTURE', 'Adventure'), ('FAMILY', 'Family'), ('SOLO', 'Solo'), ('BUSINESS_TRAVEL', 'Business Travel'), ('SHORT_BREAKS', 'Short Breaks'), ('CULINARY_TOURISM', 'Culinary Tourism')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=100)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to='accounts.user')),
            ],
        ),
    ]
