# Generated by Django 5.2.8 on 2025-11-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestay',
            name='guest_per_room',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='has_heating',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='room_rent',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='room_utils',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='guest_per_room',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_heating',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_rent',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_utils',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='guest_per_room',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='has_heating',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='room_rent',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='room_utils',
        ),
        migrations.CreateModel(
            name='HomeStayRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=20)),
                ('room_rent', models.IntegerField()),
                ('max_guest_per_room', models.IntegerField()),
                ('price_per_night', models.IntegerField()),
                ('room_utils', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestay_rooms', to='listings.homestay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=20)),
                ('room_rent', models.IntegerField()),
                ('max_guest_per_room', models.IntegerField()),
                ('price_per_night', models.IntegerField()),
                ('room_utils', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('DORM', 'Dorm'), ('PREMIUM', 'Premium')], max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='listings.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResortRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=20)),
                ('room_rent', models.IntegerField()),
                ('max_guest_per_room', models.IntegerField()),
                ('price_per_night', models.IntegerField()),
                ('room_utils', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('villa_type', models.CharField(choices=[('MOUNTAIN VIEW VILLA', 'Mountain View'), ('FARMHOUSE VILLA', 'Farmhouse Villa'), ('MODERN VILLA', 'Modern Villa'), ('BEACHFRONT VILLA', 'Beachfront Villa'), ('INFINITY POOL VILLA', 'Infinity Pool Villa'), ('COUPLE VILLA', 'Couple Ville'), ('PRESIDENTIAL SUITE', 'Presidential Suite')], max_length=30)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_rooms', to='listings.resort')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
