# Generated by Django 5.2.8 on 2025-11-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_homestay_guest_per_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestayroom',
            name='room_rent',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='room_rent',
        ),
        migrations.RemoveField(
            model_name='resortroom',
            name='room_rent',
        ),
    ]
